export const areaOfSpecializationOptions = [
  'Corporate Governance',
  'Legal Compliance',
  'Board Support',
  'Regulatory Affairs',
  'Company Law',
  'Secretarial Audits',
  'Policy Formulation',
  'Ethics and Corporate Responsibility',
  'Risk Management',
  'Shareholder Relations',
  'Corporate Communication',
  'Mergers and Acquisitions',
  'Contracts and Agreements',
  'Corporate Finance',
  'Strategic Planning',
  'Intellectual Property',
  'Environmental, Social, and Governance (ESG) Compliance',
  'Data Protection and Privacy',
  'Financial Reporting',
  'Stakeholder Management',
  'Government Liaison',
  'Litigation Support',
  'Employee Relations',
  'Training and Development',
  'Internal Controls',
  'Taxation',
  'Audit Coordination',
  'Crisis Management',
  'Sustainability Reporting',
  'Compliance Management',
  'Digital Transformation and Technology Governance',
  'Forensic Investigations',
  'Ethical Hacking and Cybersecurity',
  'International Business and Cross-Border Transactions',
  'Start-up Compliance',
  'Health and Safety Compliance',
  'Real Estate Transactions',
  'Dispute Resolution',
  'Public Relations',
  'Venture Capital and Private Equity Compliance',
  'Anti-Money Laundering (AML) Compliance',
  'Anti-Bribery and Corruption Compliance',
  'Financial Services Compliance',
  'Public Offerings and IPOs',
  'Insolvency and Bankruptcy',
  'Family Business Governance',
];
