/* eslint-disable camelcase */
export const DUMMY_DATA = {
  success: true,
  message: 'Financial data fetched successfully',
  data: {
    '2016': {
      metaData: {
        fy_end: '2016',
        stated_on: '2016-03-31',
        doc_type: 'LLPForm8',
        unit: 'inr',
        mca_form_id: 'LLP Form 8',
        documents: [
          {
            fileName: 'LLP Form8',
            s3Url: '',
            isAttachment: false,
          },
        ],
        standard_display_name: 'LLP Form 8',
      },
      liabilities: {
        contribution_received: 50000,
        reserves_and_surplus: 0,
        secured_loan: 0,
        unsecured_loan: 83495841,
        short_term_borrowing: 0,
        trade_payables: 2703757,
        other_liabilities: 0,
        other_liabilities_specific: '0',
        provisions_for_taxation: 0,
        provisions_for_contingencies: 0,
        provisions_for_insurance: 0,
        other_provisions: 12650,
        liabilities_total: 86262248,
      },
      assets: {
        gross_fixed_assets: 0,
        depreciation_and_amortization: 0,
        net_fixed_assets: 0,
        investments: 114232000,
        loans_and_advances: 0,
        inventories: 210000,
        trade_receivables: 0,
        cash_and_equivalents: 2495705,
        other_assets: -30675457,
        other_assets_specific: 'Partners Current Account',
        assets_total: 86262248,
      },
      income_statement: {
        period_from: '27/11/2015',
        period_to: '31/03/2016',
        gross_turnover: 0,
        excise_duty: 0,
        net_turnover: 0,
        dom_sale_of_goods_manufactured: 0,
        dom_sale_of_goods_traded: 0,
        dom_sale_of_services: 0,
        export_sale_of_goods_manufactured: 0,
        export_sale_of_goods_traded: 0,
        export_sale_of_services: 0,
        other_income: 0,
        stock_adjustments: 0,
        total_income: 0,
        raw_material_consumed: 0,
        purchases_for_resale: 0,
        consumption_stores: 0,
        power_and_fuel: 0,
        personnel_expenses: 0,
        administrative_expenses: 756731,
        payment_to_auditors: 0,
        selling_expenses: 0,
        insurance_expenses: 0,
        depreciation: 0,
        interest: 8438374,
        other_expenses: 0,
        total_expenditure: 9195105,
        net_profit_before_tax: -9195105,
        provision_for_tax: 0,
        profit_after_tax: -9195105,
        profit_transferred_to_partners: -9195105,
        profit_transferred_to_reserves: 0,
      },
    },
    '2017': {
      metaData: {
        fy_end: '2017',
        stated_on: '2017-03-31',
        doc_type: 'LLPForm8',
        unit: 'inr',
        mca_form_id: 'LLP Form 8',
        documents: [
          {
            fileName: 'LLP Form8',
            s3Url: '',
            isAttachment: false,
          },
        ],
        standard_display_name: 'LLP Form 8',
      },
      liabilities: {
        contribution_received: 50000,
        reserves_and_surplus: 0,
        secured_loan: 0,
        unsecured_loan: 82660559,
        short_term_borrowing: 0,
        trade_payables: 15757383,
        other_liabilities: 0,
        other_liabilities_specific: '0',
        provisions_for_taxation: 0,
        provisions_for_contingencies: 0,
        provisions_for_insurance: 0,
        other_provisions: 12290,
        liabilities_total: 98480232,
      },
      assets: {
        gross_fixed_assets: 2531250,
        depreciation_and_amortization: 0,
        net_fixed_assets: 2531250,
        investments: 120715067,
        loans_and_advances: 1944780,
        inventories: 0,
        trade_receivables: 300000,
        cash_and_equivalents: 3117586,
        other_assets: -30128451,
        other_assets_specific: 'OTHER',
        assets_total: 98480232,
      },
      income_statement: {
        period_from: '01/04/2016',
        period_to: '31/03/2017',
        gross_turnover: 0,
        excise_duty: 0,
        net_turnover: 14535000,
        dom_sale_of_goods_manufactured: 0,
        dom_sale_of_goods_traded: 0,
        dom_sale_of_services: 14535000,
        export_sale_of_goods_manufactured: 0,
        export_sale_of_goods_traded: 0,
        export_sale_of_services: 0,
        other_income: 0,
        stock_adjustments: 0,
        total_income: 14535000,
        raw_material_consumed: 0,
        purchases_for_resale: 0,
        consumption_stores: 0,
        power_and_fuel: 0,
        personnel_expenses: 0,
        administrative_expenses: 6699415,
        payment_to_auditors: 0,
        selling_expenses: 0,
        insurance_expenses: 0,
        depreciation: 281250,
        interest: 11517809,
        other_expenses: 0,
        total_expenditure: 18498474,
        net_profit_before_tax: -3963474,
        provision_for_tax: 0,
        profit_after_tax: -3963474,
        profit_transferred_to_partners: -3963474,
        profit_transferred_to_reserves: 0,
      },
    },
    '2019': {
      metaData: {
        fy_end: '2019',
        stated_on: '2019-03-31',
        doc_type: 'LLPForm8',
        unit: 'inr',
        mca_form_id: 'LLP Form 8',
        documents: [
          {
            fileName: 'LLP Form8',
            s3Url: '',
            isAttachment: false,
          },
        ],
        standard_display_name: 'LLP Form 8',
      },
      liabilities: {
        contribution_received: 50000,
        reserves_and_surplus: 0,
        secured_loan: 0,
        unsecured_loan: 149836850,
        short_term_borrowing: 0,
        trade_payables: 21132782,
        other_liabilities: 0,
        other_liabilities_specific: 'OTHERS',
        provisions_for_taxation: 7432808,
        provisions_for_contingencies: 0,
        provisions_for_insurance: 0,
        other_provisions: 13600,
        liabilities_total: 178466040,
      },
      assets: {
        gross_fixed_assets: 5090463,
        depreciation_and_amortization: 1115919,
        net_fixed_assets: 3974544,
        investments: 178372986,
        loans_and_advances: 30813922,
        inventories: 0,
        trade_receivables: 380000,
        cash_and_equivalents: 772181,
        other_assets: -35847593,
        other_assets_specific: 'OTHERS',
        assets_total: 178466040,
      },
      income_statement: {
        period_from: '01/04/2018',
        period_to: '31/03/2019',
        gross_turnover: 0,
        excise_duty: 0,
        net_turnover: 29260000,
        dom_sale_of_goods_manufactured: 0,
        dom_sale_of_goods_traded: 0,
        dom_sale_of_services: 29260000,
        export_sale_of_goods_manufactured: 0,
        export_sale_of_goods_traded: 0,
        export_sale_of_services: 0,
        other_income: 767747,
        stock_adjustments: 0,
        total_income: 30027747,
        raw_material_consumed: 0,
        purchases_for_resale: 0,
        consumption_stores: 0,
        power_and_fuel: 0,
        personnel_expenses: 0,
        administrative_expenses: 5706595,
        payment_to_auditors: 15000,
        selling_expenses: 0,
        insurance_expenses: 0,
        depreciation: 454282,
        interest: 3638180,
        other_expenses: 0,
        total_expenditure: 9814057,
        net_profit_before_tax: 20213690,
        provision_for_tax: 7432808,
        profit_after_tax: 12780882,
        profit_transferred_to_partners: 12780882,
        profit_transferred_to_reserves: 0,
      },
    },
    '2020': {
      metaData: {
        fy_end: '2020',
        stated_on: '2020-03-31',
        doc_type: 'LLPForm8',
        unit: 'inr',
        mca_form_id: 'LLP Form 8',
        documents: [
          {
            fileName: 'LLP Form8',
            s3Url: '',
            isAttachment: false,
          },
        ],
        standard_display_name: 'LLP Form 8',
      },
      liabilities: {
        contribution_received: 50000,
        reserves_and_surplus: 0,
        secured_loan: 0,
        unsecured_loan: 25296995,
        short_term_borrowing: 0,
        trade_payables: 220133309,
        other_liabilities: 0,
        other_liabilities_specific: 'OTHERS',
        provisions_for_taxation: 6078022,
        provisions_for_contingencies: 0,
        provisions_for_insurance: 0,
        other_provisions: 101,
        liabilities_total: 251558427,
      },
      assets: {
        gross_fixed_assets: 5090463,
        depreciation_and_amortization: 1523064,
        net_fixed_assets: 3567399,
        investments: 176602347,
        loans_and_advances: 14792330,
        inventories: 0,
        trade_receivables: 1559000,
        cash_and_equivalents: 7747289,
        other_assets: 47290062,
        other_assets_specific: 'OTHERS',
        assets_total: 251558427,
      },
      income_statement: {
        period_from: '01/04/2019',
        period_to: '31/03/2020',
        gross_turnover: 0,
        excise_duty: 0,
        net_turnover: 30769339,
        dom_sale_of_goods_manufactured: 0,
        dom_sale_of_goods_traded: 30769339,
        dom_sale_of_services: 0,
        export_sale_of_goods_manufactured: 0,
        export_sale_of_goods_traded: 0,
        export_sale_of_services: 0,
        other_income: 3065756,
        stock_adjustments: 0,
        total_income: 33835095,
        raw_material_consumed: 0,
        purchases_for_resale: 0,
        consumption_stores: 0,
        power_and_fuel: 0,
        personnel_expenses: 0,
        administrative_expenses: 7472142,
        payment_to_auditors: 1500,
        selling_expenses: 0,
        insurance_expenses: 0,
        depreciation: 407144,
        interest: 7536062,
        other_expenses: 0,
        total_expenditure: 15416848,
        net_profit_before_tax: 18418247,
        provision_for_tax: 6078022,
        profit_after_tax: 12340225,
        profit_transferred_to_partners: 12340225,
        profit_transferred_to_reserves: 0,
      },
    },
    '2021': {
      metaData: {
        fy_end: '2021',
        stated_on: '2021-03-31',
        doc_type: 'LLPForm8',
        unit: 'inr',
        mca_form_id: 'LLP Form 8',
        documents: [
          {
            fileName: 'LLP Form8',
            s3Url: '',
            isAttachment: false,
          },
        ],
        standard_display_name: 'LLP Form 8',
      },
      liabilities: {
        contribution_received: 50000,
        reserves_and_surplus: 0,
        secured_loan: 0,
        unsecured_loan: 0,
        short_term_borrowing: 0,
        trade_payables: 19249115,
        other_liabilities: 220297441,
        other_liabilities_specific: 'Others',
        provisions_for_taxation: 4628110,
        provisions_for_contingencies: 0,
        provisions_for_insurance: 0,
        other_provisions: 15000,
        liabilities_total: 244239666,
      },
      assets: {
        gross_fixed_assets: 3567399,
        depreciation_and_amortization: 364976,
        net_fixed_assets: 3202423,
        investments: 179279289,
        loans_and_advances: 8074394,
        inventories: 0,
        trade_receivables: 802276,
        cash_and_equivalents: 985831,
        other_assets: 51895453,
        other_assets_specific: 'others',
        assets_total: 244239666,
      },
      income_statement: {
        period_from: '01/04/2020',
        period_to: '31/03/2021',
        gross_turnover: 0,
        excise_duty: 0,
        net_turnover: 31540000,
        dom_sale_of_goods_manufactured: 0,
        dom_sale_of_goods_traded: 0,
        dom_sale_of_services: 31540000,
        export_sale_of_goods_manufactured: 0,
        export_sale_of_goods_traded: 0,
        export_sale_of_services: 0,
        other_income: 7350664,
        stock_adjustments: 0,
        total_income: 38890664,
        raw_material_consumed: 0,
        purchases_for_resale: 0,
        consumption_stores: 0,
        power_and_fuel: 0,
        personnel_expenses: 0,
        administrative_expenses: 4668305,
        payment_to_auditors: 22500,
        selling_expenses: 0,
        insurance_expenses: 0,
        depreciation: 364976,
        interest: 10348306,
        other_expenses: 0,
        total_expenditure: 15404087,
        net_profit_before_tax: 23486577,
        provision_for_tax: 4628110,
        profit_after_tax: 18858467,
        profit_transferred_to_partners: 18858467,
        profit_transferred_to_reserves: 0,
      },
    },
    '2022': {
      metaData: {
        fy_end: '2022',
        stated_on: '2022-03-31',
        doc_type: 'LLPForm8',
        unit: 'inr',
        mca_form_id: 'LLP Form 8',
        documents: [
          {
            fileName: 'LLP Form8',
            s3Url: '',
            isAttachment: false,
          },
        ],
        standard_display_name: 'LLP Form 8',
      },
      liabilities: {
        contribution_received: 50000,
        reserves_and_surplus: 0,
        secured_loan: 0,
        unsecured_loan: 0,
        short_term_borrowing: 0,
        trade_payables: 14648981,
        other_liabilities: 208744145,
        other_liabilities_specific: 'OTHERS',
        provisions_for_taxation: 0,
        provisions_for_contingencies: 0,
        provisions_for_insurance: 0,
        other_provisions: 0,
        liabilities_total: 223443126,
      },
      assets: {
        gross_fixed_assets: 4411609,
        depreciation_and_amortization: 635453,
        net_fixed_assets: 3776156,
        investments: 161069715,
        loans_and_advances: 3311661,
        inventories: 0,
        trade_receivables: 1433000,
        cash_and_equivalents: 292600,
        other_assets: 0,
        other_assets_specific: 'Other assets (to specify)',
        assets_total: 223443126,
      },
      income_statement: {
        period_from: '01/04/2021',
        period_to: '31/03/2022',
        gross_turnover: 23959428,
        excise_duty: 0,
        net_turnover: 23959428,
        dom_sale_of_goods_manufactured: 0,
        dom_sale_of_goods_traded: 0,
        dom_sale_of_services: 23959428,
        export_sale_of_goods_manufactured: 0,
        export_sale_of_goods_traded: 0,
        export_sale_of_services: 0,
        other_income: 13524126,
        stock_adjustments: 0,
        total_income: 37483554,
        raw_material_consumed: 0,
        purchases_for_resale: 0,
        consumption_stores: 0,
        power_and_fuel: 0,
        personnel_expenses: 0,
        administrative_expenses: 8448054,
        payment_to_auditors: 10000,
        selling_expenses: 0,
        insurance_expenses: 0,
        depreciation: 635453,
        interest: 10277567,
        other_expenses: 0,
        total_expenditure: 19371074,
        net_profit_before_tax: 18112480,
        provision_for_tax: 0,
        profit_after_tax: 18112480,
        profit_transferred_to_partners: 0,
        profit_transferred_to_reserves: 0,
      },
    },
    '2023': {
      metaData: {
        fy_end: '2023',
        stated_on: '2023-03-31',
        doc_type: 'LLPForm8',
        unit: 'inr',
        mca_form_id: 'LLP Form 8',
        documents: [
          {
            fileName: 'LLP Form8',
            s3Url: '',
            isAttachment: false,
          },
        ],
        standard_display_name: 'LLP Form 8',
      },
      liabilities: {
        contribution_received: 50000,
        reserves_and_surplus: 0,
        secured_loan: 0,
        unsecured_loan: 0,
        short_term_borrowing: 0,
        trade_payables: 13084467,
        other_liabilities: 161692189,
        other_liabilities_specific: 'Others',
        provisions_for_taxation: 0,
        provisions_for_contingencies: 0,
        provisions_for_insurance: 0,
        other_provisions: 0,
        liabilities_total: 174826656,
      },
      assets: {
        gross_fixed_assets: 3776156,
        depreciation_and_amortization: 653859,
        net_fixed_assets: 3122297,
        investments: 161738521,
        loans_and_advances: 3488195,
        inventories: 0,
        trade_receivables: 2317921,
        cash_and_equivalents: 751443,
        other_assets: 0,
        other_assets_specific: 'Other assets (to specify)',
        assets_total: 174826656,
      },
      income_statement: {
        period_from: '01/04/2022',
        period_to: '31/03/2023',
        gross_turnover: 33802097,
        excise_duty: 0,
        net_turnover: 33802097,
        dom_sale_of_goods_manufactured: 0,
        dom_sale_of_goods_traded: 0,
        dom_sale_of_services: 33802097,
        export_sale_of_goods_manufactured: 0,
        export_sale_of_goods_traded: 0,
        export_sale_of_services: 0,
        other_income: 814366,
        stock_adjustments: 0,
        total_income: 34616463,
        raw_material_consumed: 0,
        purchases_for_resale: 0,
        consumption_stores: 0,
        power_and_fuel: 0,
        personnel_expenses: 0,
        administrative_expenses: 26111789,
        payment_to_auditors: 15000,
        selling_expenses: 0,
        insurance_expenses: 0,
        depreciation: 653859,
        interest: 10433265,
        other_expenses: 0,
        total_expenditure: 37213913,
        net_profit_before_tax: 2597450,
        provision_for_tax: 0,
        profit_after_tax: 2597450,
        profit_transferred_to_partners: 0,
        profit_transferred_to_reserves: 0,
      },
    },
    '2024': {
      metaData: {
        fy_end: '2024',
        stated_on: '2024-03-31',
        doc_type: 'LLPForm8',
        unit: 'inr',
        mca_form_id: 'LLP Form 8',
        documents: [
          {
            fileName: 'LLP Form8',
            s3Url: '',
            isAttachment: false,
          },
        ],
        standard_display_name: 'LLP Form 8',
      },
      liabilities: {
        contribution_received: 50000,
        reserves_and_surplus: 0,
        secured_loan: 0,
        unsecured_loan: 0,
        short_term_borrowing: 0,
        trade_payables: 16542462,
        other_liabilities: 161576868,
        other_liabilities_specific: 'Others',
        provisions_for_taxation: 0,
        provisions_for_contingencies: 0,
        provisions_for_insurance: 0,
        other_provisions: 0,
        liabilities_total: 178169330,
      },
      assets: {
        gross_fixed_assets: 3459873,
        depreciation_and_amortization: 512607,
        net_fixed_assets: 2947266,
        investments: 165734545,
        loans_and_advances: 3415295,
        inventories: 0,
        trade_receivables: 0,
        cash_and_equivalents: 2656257,
        other_assets: 0,
        other_assets_specific: 'Other assets (to specify)',
        assets_total: 178169330,
      },
      income_statement: {
        period_from: '01/04/2023',
        period_to: '31/03/2024',
        gross_turnover: 37238295,
        excise_duty: 0,
        net_turnover: 37238295,
        dom_sale_of_goods_manufactured: 0,
        dom_sale_of_goods_traded: 0,
        dom_sale_of_services: 37238295,
        export_sale_of_goods_manufactured: 0,
        export_sale_of_goods_traded: 0,
        export_sale_of_services: 0,
        other_income: 624956,
        stock_adjustments: 0,
        total_income: 37863251,
        raw_material_consumed: 0,
        purchases_for_resale: 0,
        consumption_stores: 0,
        power_and_fuel: 0,
        personnel_expenses: 0,
        administrative_expenses: 5578775,
        payment_to_auditors: 0,
        selling_expenses: 0,
        insurance_expenses: 0,
        depreciation: 512607,
        interest: 10476901,
        other_expenses: 0,
        total_expenditure: 16568283,
        net_profit_before_tax: 21294968,
        provision_for_tax: 462189,
        profit_after_tax: 20832779,
        profit_transferred_to_partners: 0,
        profit_transferred_to_reserves: 0,
      },
    },
  },
};
